
package at.tuwien.sbc.task2.alternateimpl.worker.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "XMasWorkshopWarehouseService", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XMasWorkshopWarehouseService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "write", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.Write")
    @ResponseWrapper(localName = "writeResponse", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.WriteResponse")
    public void write(
        @WebParam(name = "arg0", targetNamespace = "")
        XMasWorkshopObject arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.SayHelloResponse")
    public String sayHello();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "writePart", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.WritePart")
    @ResponseWrapper(localName = "writePartResponse", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.WritePartResponse")
    public void writePart(
        @WebParam(name = "arg0", targetNamespace = "")
        ProductionElf arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2);

    /**
     * 
     * @return
     *     returns java.util.List<at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.TeddyBear>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTeddyBears", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.FindTeddyBears")
    @ResponseWrapper(localName = "findTeddyBearsResponse", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.FindTeddyBearsResponse")
    public List<TeddyBear> findTeddyBears();

    /**
     * 
     * @return
     *     returns java.util.List<at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.XMasWorkshopObject>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTeddyParts", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.FindTeddyParts")
    @ResponseWrapper(localName = "findTeddyPartsResponse", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.FindTeddyPartsResponse")
    public List<XMasWorkshopObject> findTeddyParts();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "tryToAssembleTeddyBear", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.TryToAssembleTeddyBear")
    @ResponseWrapper(localName = "tryToAssembleTeddyBearResponse", targetNamespace = "http://tuwien.ac.at/sbc/task2/XMasWorkshopWarehouseService", className = "at.tuwien.sbc.task2.alternateimpl.worker.webservice.client.TryToAssembleTeddyBearResponse")
    public void tryToAssembleTeddyBear(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
